# ================= APPLICATION =================
spring.application.name=rigs
server.port=8080

# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= FLYWAY =================
spring.flyway.baseline-on-migrate=true
spring.flyway.repair-at-start=true
spring.flyway.validate-on-migrate=false

# ================= THYMELEAF =================
spring.thymeleaf.cache=false

# ================= GOOGLE OAUTH =================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# Optional but recommended (Spring usually infers this)
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# ================= EMAIL CONFIG =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=INFO

# ================= FRONTEND URL =================
rigs.frontend.url=${FRONTEND_URL:http://localhost:5173}

# ================= FILE UPLOAD =================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
rigs.upload.dir=./uploads

# ================= MQTT =================
mqtt.broker.url=ssl://802966d9c99f48a3a2436e3eacd58939.s1.eu.hivemq.cloud:8883
mqtt.client.id=rigs-backend-${random.uuid}
mqtt.username=rigs_client
mqtt.password=Kanzariya2413
